---
abstract: 'A structured event logger for Fluent'
author:
  - 'HIROSE Masaaki <hirose31 _at_ gmail.com>'
build_requires:
  Capture::Tiny: 0
  ExtUtils::MakeMaker: 6.36
  Path::Class: 0
  Test::More: 0.88
  Test::SharedFork: 0
  Test::TCP: 1.3
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fluent-Logger
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Fluent::Logger:
    file: lib/Fluent/Logger.pm
    version: 0.12
requires:
  Data::MessagePack: 0.35_01
  Mouse: 0
  Time::Piece: 0
resources:
  bugtracker: https://github.com/fluent/fluent-logger-perl/issues
  homepage: https://github.com/fluent/fluent-logger-perl
  repository: git://github.com/fluent/fluent-logger-perl.git
version: 0.12
x_contributors:
  - 'HIROSE Masaaki <hirose31@gmail.com>'
  - 'Shinichiro Sei <sei@kayac.com>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'koji_magi <kadal_keys@hotmail.co.jp>'
  - 'tokuhirom <tokuhirom@gmail.com>'
  - 'cho45 <cho45@lowreal.net>'
  - 'Tomohiro Hosaka <bokutin@bokut.in>'
  - 'Brian Fraser <fraserbn@gmail.com>'
  - 'FUJIWARA Shunichiro <fujiwara.shunichiro@gmail.com>'
